version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - ${APP_PORT}:6667
    networks:
      - default
    stdin_open: true
    tty: true

networks:
  default:
    name: docker_irssi_network
    driver: bridge

volumes:
  data:
    name: docker_irssi_data
    driver: local